### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by zhiqiaoprc** [xuekt98/BBDM#19]
I try to train a paired style transfer with custom dataset. But results are weird.
![Uploading output_2.png…]()

**Comment by zhiqiaoprc** [comment]
![output_2](https://github.com/xuekt98/BBDM/assets/36597531/8414822f-9937-4b14-ba24-fa52c19d288f)

**Comment by chamathabeysinghe** [comment]
@zhiqiaoprc Did you manage to solve this problem?

**Comment by barkindagda** [comment]
I have the same issue. Can you please help @zhiqiaoprc ?

**Comment by Lewislou** [comment]
I have the same problem. How to solve this?

**Comment by lyqun** [comment]
I have the same problem. Was this issue solved, and why is this issue closed?
