### ISSUE TITLE
When I create the environment I encounter this error. How can I fix it?

### ISSUE THREAD

**Issue by gabriel-nkole** [xuekt98/BBDM#26]
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0)
ERROR: No matching distribution found for torch==1.12.1+cu113

failed

CondaEnvException: Pip failed

**Comment by gabriel-nkole** [comment]
To fix the "Could not find a version that satisfies..." errors I just removed the lines for installing torch, torchvision & torchaudio from the environment.yml and manually installed my own versions.

**Comment by SarielMa** [comment]
I met the same issue.
